# Generated by Django 3.1.1 on 2020-12-05 11:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('frame', '0005_auto_20201205_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='framepage',
            name='history',
            field=wagtail.core.fields.StreamField([('history', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('hi', wagtail.core.blocks.PageChooserBlock(required=False)), ('hello', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True, verbose_name='历史效果图'),
        ),
        migrations.AlterField(
            model_name='cardpage',
            name='img',
            field=models.ForeignKey(blank=True, help_text='图案', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='cardpage',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='预览图', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='framepage',
            name='bottom',
            field=models.ForeignKey(blank=True, help_text='框底部', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='framepage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code')), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('raw_HTML', wagtail.core.blocks.RawHTMLBlock()), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('audio_block', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(label='Audio name'))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-paragraph', template='blocks/embed_block.html'))], blank=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='framepage',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='预览图', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='framepage',
            name='top',
            field=models.ForeignKey(blank=True, help_text='框顶部', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='scenepage',
            name='img',
            field=models.ForeignKey(blank=True, help_text='图案', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='scenepage',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='预览', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
