# Generated by Django 3.1.1 on 2020-12-05 11:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0007_auto_20201205_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framepage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code')), ('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('raw_HTML', wagtail.core.blocks.RawHTMLBlock()), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('audio_block', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(label='Audio name'))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-paragraph', template='blocks/embed_block.html'))], blank=True, verbose_name='介绍'),
        ),
    ]
