# Generated by Django 3.1.1 on 2020-12-05 11:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0008_auto_20201205_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framepage',
            name='history',
            field=wagtail.core.fields.StreamField([('history', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('frame_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('card_page', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True, verbose_name='历史效果图'),
        ),
    ]
