# Generated by Django 3.1.1 on 2020-12-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('frame', '0009_auto_20201205_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpage',
            name='img',
            field=models.ForeignKey(blank=True, help_text='图案', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='图案'),
        ),
        migrations.AlterField(
            model_name='cardpage',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='预览图', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='预览图'),
        ),
        migrations.AlterField(
            model_name='framepage',
            name='bottom',
            field=models.ForeignKey(blank=True, help_text='框底部', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='框底部'),
        ),
        migrations.AlterField(
            model_name='framepage',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='预览图', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='预览图'),
        ),
        migrations.AlterField(
            model_name='framepage',
            name='top',
            field=models.ForeignKey(blank=True, help_text='框顶部', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='框顶部'),
        ),
        migrations.AlterField(
            model_name='scenepage',
            name='img',
            field=models.ForeignKey(blank=True, help_text='图案', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='图案'),
        ),
        migrations.AlterField(
            model_name='scenepage',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='预览', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='预览'),
        ),
    ]
