# Generated by Django 3.1.6 on 2021-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0014_auto_20210220_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='framepage',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
