# Generated by Django 3.1.6 on 2021-02-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0015_framepage_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framepage',
            name='width',
            field=models.FloatField(blank=True, help_text='单位为厘米', null=True, verbose_name='框条宽度'),
        ),
    ]
